// app/[locale]/layout.tsx
import '../globals.css';

import {NextIntlClientProvider} from 'next-intl';
import {getMessages, unstable_setRequestLocale} from 'next-intl/server';
import type {Metadata} from 'next';

export const metadata: Metadata = {
  title: 'Real Estate GenAI',
  description: 'AI-powered real estate search'
};

// Pre-generate the two locales you use
export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'ar' }];
}

export default async function LocaleLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: 'en' | 'ar' };
}) {
  // Inform next-intl about the active locale for this request
  unstable_setRequestLocale(locale);

  // Load messages generated by next-intl during the build/runtime
  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}